// Plan (self-reviewed), implement per task, update docs, then open a PR.
//> using scala 3.9.0
//> using dep "org.virtuslab::orca:0.1.9"
//> using jvm 21

/** Autonomous planning + coding flow that lands the work on its own branch and
  * opens a pull request.
  *
  * Same backbone as `implement.sc` (autonomous planning → per-task implement +
  * single review pass → whole-run review loop), plus two additions: the planner
  * critiques its own draft and returns an improved one (missing or duplicated
  * tasks, ordering, vague descriptions, steps that don't fit the code), and a
  * documentation stage updates the project's docs from what the tasks changed,
  * so they land in the PR and the final review covers them.
  *
  * A PR follows when the repository is on GitHub, its title and description
  * generated by a cheap model from the full branch diff; otherwise the run says
  * so and ends on the feature branch, work committed either way.
  *
  * ```bash
  * scala-cli run --workspace "$(mktemp -d)" implement-enhanced.sc -- "Add a multiply function to the calculator crate"
  * ```
  *
  * Requires the configured role agents logged in (`claude` by default); `gh` is
  * optional.
  */

import orca.{*, given}

flow(OrcaArgs(args)):
  val plan = stage("Plan"):
    Plan.autonomous
      .from(userPrompt, planningAgent)
      .reviewed()
      .value

  val taskOpenFindings =
    for task <- plan.tasks yield
      stage(s"Task: ${task.title}"):
        val session = codingAgent.session("implementer", seed = plan.brief)
        session.run(task.description)
        reviewThenFix(
          coderSession = session,
          reviewers = allReviewers(reviewAgent),
          task = task
        )

  // Its own stage, so the docs commit exists before the push below. The
  // documenter implemented none of the tasks, so the prompt points it at the
  // branch diff for what actually changed.
  stage("Update documentation"):
    val documenter = codingAgent.session("documenter", seed = plan.brief)
    documenter.run(
      "All tasks are done and committed. Read what this branch changed " +
        "(`git diff` against its base), then update project docs (README, " +
        "doc-comments) to match. Only update what's affected — no new sections."
    )

  // Nothing reviews again after this loop, hence the raised iteration cap.
  val openFindings = stage("Final review"):
    val finalFixer = codingAgent.session("final-fixer", seed = plan.brief)
    reviewAndFixLoop(
      coderSession = finalFixer,
      reviewers = allReviewers(reviewAgent),
      task = Task(Title("The whole planned change"), plan.brief),
      diff = ReviewDiff.WholeRun,
      maxIterations = 5,
      priorOpenFindings = taskOpenFindings.flatMap(_.findings)
    )

  openPrIfGitHub(
    summarisingAgent = codingAgent.cheap,
    openFindings = openFindings
  )
